package com.decimal128.decimal

enum class InvalidCause {
    NAN_OPERAND,       // an operand was a NaN
    SNAN_OPERAND,      // An operand was an sNaN
    MAGNITUDE_SUBTRACTION_OF_INFINITIES, // e.g., (+∞) + (-∞)
    MUL_ZERO_BY_INFINITY, // e.g., 0 * ∞
    DIV_ZERO_BY_ZERO,
    DIV_INF_BY_INF,
    DIV_BY_ZERO_IN_REMAINDER_OP,
    INF_NUMERATOR_IN_REMAINDER_OP,
    UNABLE_TO_SCALE,
    PARSE_MALFORMED,
    PARSE_EMPTY_STRING,
    PARSE_DOUBLE_DOT,
    PARSE_INVALID_UNDERSCORE_LOCATION,
    PARSE_NO_EXPONENT_DIGIT,
    PARSE_UNEXPECTED_CHAR,
    PARSE_NO_COEFFICIENT_DIGIT,
    PARSE_COEFFICIENT_EXCEEDS_MAX_PRECISION,
    PARSE_VALUE_OUT_OF_RANGE,
    PARSE_NON_DIGIT_AFTER_NAN,
    PARSE_NAN_PAYLOAD_TOO_LONG,
    SQUARE_ROOT_OF_NEG_FINITE_NON_ZERO,        // e.g., sqrt(-1)
    SQUARE_ROOT_OF_NEG_INFINITY,
    LOG_OF_NEG_VALUE,
    LOG_OF_NEG_NUMBER,
    POWER_OF_NEG_BASE_NON_INTEGER_EXPONENT,
    COMPOUND_X_LT_NEG_ONE,
    COMPOUND_ARGS_INVALID,
    ROOTN_BAD_ARGS,
    QUANTUM_SCALE_OUT_OF_RANGE,
    QUANTIZE_RESULT_WOULD_EXCEED_PRECISION,
    QUANTIZE_EXACTLY_ONE_OPERAND_IS_INFINITE,
    QUANTUM_OF_NON_FINITE,
    DIV_INT_OVERFLOWS_COEFFICIENT, // 9999999999999999999999999999999999 / .0000000000000001
    CONVERT_NON_FINITE_TO_INTEGER,
    OTHER,
}